version: '2'

services:

    webapp:
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: always
        hostname: webapp
        ports:
            - "80:80"
        environment:
            - SEARCH_FROM_MAIL=
            - SEARCH_SMTP_SERVER=
            - SEARCH_SMTP_PORT=
