version: '2'

services:

    mailhog:
        image: mailhog/mailhog:latest
        hostname: mailhog
        ports:
            - "1025:1025"
            - "8025:8025"
    webapp:
        build:
            context: .
            dockerfile: ./Dockerfile-dev
        restart: always
        hostname: webapp
        depends_on:
            - mailhog
        volumes:
            - ./iahx:/var/www/site # SciELO Search Journals
        links:
            - mailhog:mailhog
        ports:
            - "80:80"
        environment:
            - SEARCH_SOLR_CORE=solr/scielo-test
            - SEARCH_USE_HTTPS=false
            - SEARCH_SOLR_SERVER=api-search.scielo.org

